# Site settings
title: AI Tools Collection
description: A comprehensive collection of AI-related tools, prompts, instructions, and documentation for personal use.
baseurl: "/ai-tools" # the subpath of your site, e.g. /blog
url: "https://maugx3.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

# Theme configuration
# Using Just the Docs - a modern, responsive documentation theme
# https://just-the-docs.github.io/just-the-docs/
theme: just-the-docs

# Just the Docs theme customization
# Enable/disable features
search_enabled: true
heading_anchors: true

# Color scheme (light/dark mode support)
color_scheme: light

# Appearance settings
logo: false
favicon_ico: false

# Navigation
nav_sort: case_insensitive

# Footer content
footer_content: "© 2025 AI Tools Collection. Licensed under MPL 2.0."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  prompts:
    output: true
    permalink: /:collection/:name/
  instructions:
    output: true
    permalink: /:collection/:name/
  modes:
    output: true
    permalink: /:collection/:name/
  thoughts:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Prompts
    url: /prompts/
  - title: Instructions
    url: /instructions/
  - title: Modes
    url: /modes/
  - title: Documentation
    url: /docs/
  - title: Thoughts
    url: /thoughts/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "prompts"
    values:
      layout: "prompt"
      category: "prompt"
  - scope:
      path: ""
      type: "instructions"
    values:
      layout: "instruction"
      category: "instruction"
  - scope:
      path: ""
      type: "modes"
    values:
      layout: "mode"
      category: "mode"
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: "thought"
      category: "thought"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docs/README.md
