# Site settings
title: AI Tools Collection
description: A comprehensive collection of AI-related tools, prompts, instructions, and documentation for personal use.
baseurl: "/ai-tools" # the subpath of your site, e.g. /blog
url: "https://maugx3.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

# Theme configuration
# Using Just the Docs - a modern, responsive documentation theme
# https://just-the-docs.github.io/just-the-docs/
theme: just-the-docs

# Just the Docs theme customization
# Enable/disable features
search_enabled: true
heading_anchors: true
aux_links_new_tab: true

# Color scheme - using a modern, friendly color scheme
color_scheme: "custom"

# Callouts for better visual hierarchy
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Appearance settings
logo: false
favicon_ico: false

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/MauGx3/ai-tools

# Footer content
footer_content: "© {{ site.time | date: '%Y' }} AI Tools Collection. Licensed under <a href=\"https://www.mozilla.org/en-US/MPL/2.0/\">MPL 2.0</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Mermaid diagrams support
mermaid:
  version: "10.6.1"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  prompts:
    output: true
    permalink: /:collection/:name/
  instructions:
    output: true
    permalink: /:collection/:name/
  modes:
    output: true
    permalink: /:collection/:name/
  thoughts:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "prompts"
    values:
      layout: "default"
      parent: "Prompts"
  - scope:
      path: ""
      type: "instructions"
    values:
      layout: "default"
      parent: "Instructions"
  - scope:
      path: ""
      type: "modes"
    values:
      layout: "default"
      parent: "Modes"
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: "default"
      parent: "Thoughts"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docs/README.md
