name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: CHANGELOG_LATEST.md

      - name: Update CHANGELOG.md
        uses: orhun/git-cliff-action@v4
        with:
          config: .cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG_LATEST.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git diff --staged --quiet || git commit -m "docs(changelog): update changelog for ${{ github.ref_name }}"
          git push origin HEAD:${{ github.event.repository.default_branch }} || echo "No changes to push"
